FROM p.home.forgame.com:4567/docker/lnp:centos7_nginx1.8.1_php7.1

MAINTAINER dockerzsm zhangshimiande@gmail.com

COPY ./conf/nginx.conf /usr/local/nginx/conf/nginx.conf
COPY ./conf/php.ini /usr/local/php/etc/php.ini